FROM node:14-alpine

ENV CONTAINER=true

WORKDIR /app

RUN apk add --no-cache curl

RUN curl -OL https://raw.githubusercontent.com/mrako/wait-for/master/wait-for && chmod +x wait-for

COPY ./package*.json ./

RUN npm ci --production=false

COPY ./tsconfig.json ./

RUN npm install -g ts-node typescript

COPY ./src ./src

COPY ./ormconfig.js ./

COPY ./resources ./resources

CMD [ "npm", "test" ]