version: "3.8"

services: 
  bot:
    privileged: true
    container_name: bot
    build: ./
    image: yey007/transcriberbot:latest
    restart: always
    command: sh -c "./wait-for db:3306 -- npm start"
    env_file: 
      - ./resources/bot.env
      - ./resources/db.env
    environment:
      - NODE_ENV=production
    depends_on: 
      - db
    networks:
      - my_network

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./resources/db.env
    expose: 
      - 3306
    networks:
      - my_network
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
