version: '3.8'

services:
  sut:
    privileged: true
    container_name: bot
    build: ./
    image: yey007/transcriberbot:latest
    command: sh -c "./wait-for db:3306 -- npm test"
    env_file:
      - ./bot.env
      - ./db.env
      - ./test.env
    environment:
      - NODE_ENV=testing
    depends_on:
      - db
    networks:
      - my_network
    tty: true

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./db.env
    expose:
      - 3306
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
