version: '3.8'

services:
  sut:
    privileged: true
    container_name: bot
    build: ./
    image: yey007/transcriberbot:latest
    command: sh -c "./wait-for db:3306 -- npm test"
    environment:
      - DISCORD_TOKEN
      - WATSON_SPEECH_API_KEY
      - WATSON_SPEECH_URL
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - DISCORD_TEST_TOKEN
      - TESTING_CHANNEL_ID
      - TESTING_VOICE_CHANNEL_ID
      - PREFIX
      - NODE_ENV=testing
    depends_on:
      - db
    networks:
      - my_network
    tty: true

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    expose:
      - 3306
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
