FROM node:14-alpine

ENV CONTAINER=true

WORKDIR /app

RUN apk add --no-cache curl

RUN curl -OL https://raw.githubusercontent.com/mrako/wait-for/master/wait-for && chmod +x wait-for

COPY ./package*.json ./

RUN npm ci --production=false

COPY ./tsconfig.json ./

RUN npm install -g typescript

COPY ./src ./src

RUN tsc -p tsconfig.json

COPY ./database.json ./

COPY ./resources ./resources

COPY ./migrations ./migrations

CMD [ "npm", "test" ]