name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: transcriberbot
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  WATSON_SPEECH_API_KEY: ${{ secrets.WATSON_SPEECH_API_KEY }}
  WATSON_SPEECH_URL: ${{ secrets.WATSON_SPEECH_URL }}
  MYSQL_ROOT_PASSWORD: bruh
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: transcriberbot
  MYSQL_USER: transcriberbot
  DISCORD_TEST_TOKEN: ${{ secrets.DISCORD_TEST_TOKEN }}
  TESTING_CHANNEL_ID: "778808634226245663"
  TESTING_VOICE_CHANNEL_ID: "780612930684977173"
  PREFIX: "!"

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.github.test.yml ]; then
            docker-compose --file docker-compose.github.test.yml build
            docker-compose --file docker-compose.github.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: yey007/${{ IMAGE_NAME }}
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ IMAGE_NAME }}
          tag_with_ref: true
