name: REEEE

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: transcriberbot
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          id: docker_build
          push: true
          tags: |
            yey007/transcriberbot:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
